require('dotenv').config();

export const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.FIREBASE_DATABASE_URL,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
};

export const words = [
  '1. É minha',
  '2. 3 toques',
  '3. deixa',
  '4. saaai!',
  '5. comunicação!!',
  '6. foraaa',
  '7. Na rede é peixe',
  '8. errrou',
  '9. cade a cobertura',
  '10. bom saque',
  '11. de graça',
  '12. fundoo',
  '13. era minha?',
  '14. era tua!',
  '15. saque trenó',
  '16. calma a bola',
  '17. Duas mãos',
  '18. Que paraleluda!',
  '19. Bora time',
  '20. A boa!',
  '21. Vai a dois',
  '22. Pula',
  '23. Recepção',
  '24. Vamo tirar',
  '25. bloqueioo',
  '26. não gira',
  '27. quebra a mão',
  '28. marca lá',
  '29. tem jogo',
  '30. repeteee',
];
